version: '3'


networks:
  net:
    driver: bridge

services:
  dev:
    build:
      context: ./docker/app
      args:
        DEBUG: 1
    volumes:
      - ./:/var/www
    working_dir: /var/www
    networks:
      - net
    depends_on:
      - elasticsearch
    ports:
      - ${SERVE_PORT}:${SERVE_PORT}
    tty: true
  app:
    build:
      context: ./docker/app
    volumes:
      - ./:/var/www
    working_dir: /var/www
    ports:
      - ${SERVE_PORT}:${SERVE_PORT}
    networks:
      - net
    depends_on:
      - elasticsearch
    restart: on-failure
    command:
      - /bin/sh
      - -c
      - |
        go build -o ./main .
        ./main
    tty: true
  elasticsearch:
    build:
      context: ./docker/elasticsearch
    volumes:
      - ./data:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - net
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "${ELASTICSEARCH_HOST_HTTP_PORT}:9200"